name: Java CI

on:
  push:
    # Run on the main branch
    branches:
      - main
  # Also on PRs, just be careful not to publish anything
  pull_request:
  # Allow to be called from other workflows (like "release")
  workflow_call:
  # But don't trigger on tags, as they are covered by the "release.yaml" workflow

jobs:
  policy-vulnerability-check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Install Seedwing CLI
        run: cargo install --git https://github.com/seedwing-io/seedwing-policy.git --branch main seedwing-policy-cli

      - name: Test
        run: cd java && ./mvnw test

      - name: Generate SBOM
        run: cd java && ./mvnw package

      - name: Check dependencies for vulnerabilities
        run: seedwing-policy-cli -p policies eval --name vulnerabilities::not-affected-fast < java/target/bom.json
